# Generated by Django 3.2.11 on 2022-04-24 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('question', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('P', 'Political Involvement'), ('S', 'Social Responsibility'), ('C', 'Commmunity Service')], max_length=1, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('P', 'Political Involvement'), ('S', 'Social Responsibility'), ('C', 'Commmunity Service')], max_length=1)),
                ('numRight', models.IntegerField(null=True)),
                ('totalQuestions', models.IntegerField(default=10)),
                ('percent', models.FloatField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
