# Generated by Django 3.2.11 on 2022-04-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='category',
            field=models.CharField(choices=[('P', 'Political Involvement'), ('S', 'Social Responsibility'), ('C', 'Commmunity Service')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='quizcategorymodel',
            name='category',
            field=models.CharField(choices=[('P', 'Political Involvement'), ('S', 'Social Responsibility'), ('C', 'Commmunity Service')], max_length=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
