# Generated by Django 3.2.11 on 2022-04-21 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizcategorymodel',
            name='category',
            field=models.CharField(choices=[('P', 'Political Involvement'), ('S', 'Social Responsibility'), ('C', 'Commmunity Service')], default=django.utils.timezone.now, max_length=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
