# Generated by Django 3.2.11 on 2022-04-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infohub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='quizinformation',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
