# Generated by Django 3.2.11 on 2022-04-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
