# Generated by Django 3.2.11 on 2022-04-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20220411_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizinformation',
            name='username',
        ),
        migrations.AddField(
            model_name='quizinformation',
            name='article_title',
            field=models.CharField(default='Some string', max_length=1000),
        ),
    ]
