# Generated by Django 3.2.11 on 2022-04-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20220421_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='answer',
            new_name='ans',
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quizcategorymodel',
            name='category',
            field=models.CharField(choices=[('P', 'Political Involvement'), ('S', 'Social Responsibility'), ('C', 'Commmunity Service')], max_length=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
