# Generated by Django 3.2.11 on 2022-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('event_location', models.CharField(max_length=500)),
                ('event_date', models.DateTimeField()),
                ('event_link', models.CharField(max_length=500)),
            ],
        ),
    ]
