# Generated by Django 3.2.11 on 2022-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.BooleanField(default=False),
        ),
    ]
