# Generated by Django 3.2.11 on 2022-04-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.CharField(default=None, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
