# Generated by Django 3.2.11 on 2022-04-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='user_id',
        ),
    ]
