# Generated by Django 3.2.11 on 2022-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_rename_user_id_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
